### ISSUE TITLE
close 'anyone but rms' loophole

### ISSUE THREAD

**Issue by makc** [landondyer/kasm#2]
as long as you say anyone (but rms) can do anything, they can change the terms of license (part of 'anything') and let rms in. you should specifically disallow licensing changes, similarly to gnu license :)

**Comment by landondyer** [comment]
I didn't stipulate that, and given the whimsical nature of the license I don't feel strongly moved to amend it. You win :-)

[Most people realize the whimsy, but a few have taken it fairly seriously. I'm fine with RMS himself asking me to change the license, but I don't think that anyone else should care, and RMS won't ask.]

--------- Original Message --------- Subject: [kasm] close 'anyone but rms' loophole (#2)

**Comment by joaohornburg** [comment]
Serious issue! Should be fixed ;)

**Comment by Maia-Everett** [comment]
Actually, while the license did elicit a laugh from me, I have doubts about it as it is GPL incompatible, adding an additional restriction beyond the provisions of the GPL.

**Comment by makc** [comment]
@Sikon but you can (which is this issue point) make your fork and re-license it under GPL, then it's compatible.
