### ISSUE TITLE
Possible license change

### ISSUE THREAD

**Issue by iainx** [landondyer/kasm#4]
Would you consider changing to a license closely related to the ABRMS license but slightly more complex? I'm obviously talking about the "Anyone But Richard M Stallman or Eric S Raymond" (ABRMSOESR) license?

**Comment by pwarren** [comment]
Nah, go for the GPLv3 it's the future of Open Source.

**Comment by landondyer** [comment]
I don’t have any reason to extend the limitations to ESR.  Additionally, it would make the name of the license harder to pronounce.

So, no. Obviously anyone can instantiate the ABRMSOESR license on their own work, but not to kasm.

Keep thinking happy thoughts. :)

**Comment by iainx** [comment]
Fair enough. I'll close this then
