### ISSUE TITLE
Please consider switching to a free software license

### ISSUE THREAD

**Issue by mattl** [landondyer/kasm#5]
the WTFPL would be fine, if you're looking for a very minimal license.

**Comment by landondyer** [comment]
Not going to do that. But thanks.

Think of it as performance art :-)

--------- Original Message --------- Subject: [kasm] Please consider switching to a free software license (#5)

**Comment by mattl** [comment]
Gah, okay. Can't use it then, I'm afraid.

**Comment by landondyer** [comment]
Okay. Plenty of assemblers out there, good luck.

-l

--------- Original Message --------- Subject: Re: [kasm] Please consider switching to a free software license (#5)

**Comment by ghost** [comment]
@mattl 
Why can't you use it?
Are you Richard M Stallman?
If not you clearly can use it.
