### ISSUE TITLE
license is contradictory

### ISSUE THREAD

**Issue by LSWdigital** [landondyer/kasm#6]
‘No other licences may apply’ and ‘Do anything you want with this program, with the exceptions listed under "EXCEPTIONS"’ seem to be in conflict.

**Comment by landondyer** [comment]
Seems pretty clear to me. You can’t apply a different license.

(Sent from my phone, please forgive typos)

**Comment by LSWdigital** [comment]
But this is a restriction not ‘listed under "EXCEPTIONS"’, so I can't do anything I want.

**Comment by wallace-aph** [comment]
The license is hilarious, I reference it often. Would be sad if you changed it!
